### ISSUE TITLE
Sugerencia nombre menú

### ISSUE THREAD

**Issue by eduromo** [jact/odfinder#1]
La entrada en el menú de aplicaciones con un sistema en Español es "Open Document Finder"

En mi opinión debería tener un nombre convenientemente "españolizado"

Sugerencia

Buscador contenido ODF

**Comment by jact** [comment]
Ese es el nombre de la aplicación y, por lo tanto, no puede ser "españolizada". Sería como si a Thunderbird se le denominara "Pájaro del trueno" o a OpenOffice, "Oficina abierta". No tendría sentido.

Es el nombre del producto.
